server:
  port: 8014
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID
        domain: test.spring

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
    sender: 
      type: web
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: redis
    port: 6379
    database: 0
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud: DEBUG
