server:
  port: 8014
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: redis-service
    port: 6379
    database: 0
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        userAuthorizationUri: http://oauth2-service:8016/oauth/authorize
        accessTokenUri: http://oauth2-service:8016/oauth/access_token
        clientAuthenticationScheme: form
      resource:
        userInfoUri: http://oauth2-service:8016/user/info
        preferTokenInfo: false

logging:
  level:
    org.springframework.cloud: DEBUG
