server:
  port: 8016
  servlet:
    session:
      cookie:
        name: OAUTH2-SERVER-SESSIONID

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin-service/
  sleuth:
    sampler:
      probability: 1.0

  redis:
    host: redis-service
    port: 6379
    database: 0

  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud: DEBUG
