server:
  port: 8010

InstanceDiscovery:
  impl: com.netflix.turbine.discovery.ConfigPropertyBasedDiscovery

turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  ConfigPropertyBasedDiscovery: 
    default: 
      instances: http://zuul,http://oauth2,http://business,http://business2
  combine-host-port: true
    eureka:
      enabled: false
spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
