server:
  port: 8010

turbine:
  app-config: zuul,oauth2,business,business2
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true

spring:
  zipkin:
    baseUrl: http://zipkin-service/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
