server:
  port: 8010

InstanceDiscovery:
  impl: com.netflix.turbine.discovery.ConfigPropertyBasedDiscovery

turbine:
  aggregator:
    cluster-config: zuul,oauth2,business,business2
  ConfigPropertyBasedDiscovery: 
    zuul: 
      instances: zuul
    oauth2: 
      instances: oauth2
    business: 
      instances: business
    business2: 
      instances: business2

  instanceUrlSuffix:
      zuul: :8086/actuator/hystrix.stream
      oauth2: :8016/actuator/hystrix.stream
      business: :8088/actuator/hystrix.stream
      business2: :8014/actuator/hystrix.stream

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
