server:
  port: 8010

InstanceDiscovery:
  impl: com.netflix.turbine.discovery.ConfigPropertyBasedDiscovery

turbine:
  aggregator:
    cluster-config: default
  ConfigPropertyBasedDiscovery: 
    default: 
      instances: zuul:8086,oauth2:8016,business:8088,business2:8014
  instanceUrlSuffix:
    default: /actuator/hystrix.stream

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
