server:
  port: 8010

InstanceDiscovery:
  impl: com.netflix.turbine.discovery.ConfigPropertyBasedDiscovery

turbine:
  aggregator:
    cluster-config: default
  ConfigPropertyBasedDiscovery: 
    default: 
      instances: zuul,oauth2,business,business2
    instanceUrlSuffix:
        zuul: :8086/actuator/hystrix.stream
    instanceUrlSuffix:
        oauth2: :8016/actuator/hystrix.stream
    instanceUrlSuffix:
        business: :8088/actuator/hystrix.stream
    instanceUrlSuffix:
        business2: :8014/actuator/hystrix.stream

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
