
server:
  port: 8012

management:
  metrics:
    web:
      server:
        auto-time-requests: false

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
