server:
  port: 8086
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID
        domain: test.spring

management:
  endpoints:
    web:
      exposure:
        include: *

spring:
  zipkin:
    baseUrl: http://zipkin:8012/
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: redis
    port: 6379
    database: 0

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


zuul:
  routes:
    business:
      path: /business/**
      sensitiveHeaders:
      url: http://business:8088/
    business2:
      path: /business2/**
      sensitiveHeaders:
      url: http://business2:8014/
  ratelimit:
    enabled: true
    repository: REDIS
    default-policy:
      limit: 30
      refresh-interval: 5
      type: origin


logging:
  level:
    org.springframework.cloud: DEBUG
